name: Update chart data and deploy to GitHub Pages

on:
  push:
    branches:
      - main # 监听main分支的推送
  schedule:
    - cron: "0 5 * * 1-5" # UTC时间凌晨5:00触发（东部时间 0点/1点 ）

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install Python dependencies
        run: |
          pip install requests pandas

      - name: Run Python scripts
        env:
          ALPHA_VANTAGE_API_KEY: ${{ secrets.ALPHA_VANTAGE_API_KEY }}
        run: |
          cd backend
          python get_csv.py
          python get_current_month.py
          python get_filtered.py
          python get_summary.py
          python get_json.py

      - name: Copy JSON files to React public directory
        run: |
          cp -r backend/JSON/* frontend/option-tech-charts/public/data/

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ">=18.x"

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: frontend/option-tech-charts/node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('frontend/option-tech-charts/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      - name: Install npm dependencies
        working-directory: frontend/option-tech-charts
        run: npm install

      - name: Build React app
        working-directory: frontend/option-tech-charts
        run: npm run build:deploy

      - name: Clone external repository
        run: |
          git clone https://${{ secrets.DEPLOY_TOKEN }}@github.com/Aaakul/Aaakul.github.io.git
          cd Aaakul.github.io
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@noreply.github.com"
      
      - name: Clean destination directory
        run: |
          rm -rf ./Aaakul.github.io/option-tech-charts/*
          mkdir -p ./Aaakul.github.io/option-tech-charts/    

      - name: Copy build files to external repository
        run: |
          cp -r ./frontend/option-tech-charts/build/* ./Aaakul.github.io/option-tech-charts/
          cd Aaakul.github.io
          git add .
          # 检查是否有更改
          if git diff-index --quiet HEAD; then
            echo "No changes to commit"
          else
            git commit -m "Deploy to GitHub Pages"
            git push --set-upstream origin gh-pages
          fi
