name: Update chart data and deploy to GitHub Pages

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 5 * * 1-5" # UTC AM 5:00 (ET 0/1:00 ）

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
          cache: 'pip' # caching pip dependencies

      - name: Install Python dependencies
        run: |
          pip install -r ./backend/requirements.txt

      - name: Clean files
        run: |
          rm -rf backend/data/*
          rm -rf backend/JSON/*

      - name: Run Python scripts
        env:
          ALPHA_VANTAGE_API_KEY: ${{ secrets.ALPHA_VANTAGE_API_KEY }}
        run: |
          cd backend
          chmod +x run_scripts.sh
          ./run_scripts.sh

      # - name: Check JSON files
      #   run: |
      #     md5_backend=$(md5sum backend/data/JSON/SPY/SPY_0dte.json | awk '{ print $1 }')
      #     md5_frontend=$(md5sum frontend/option-tech-charts/public/data/SPY/SPY_0dte.json | awk '{ print $1 }')
          
      #     if [ "$md5_backend" = "$md5_frontend" ]; then
      #       echo "The files have the same content."
      #     else
      #       echo "The files have different content."
      #       exit 1
      #     fi

      - name: Copy JSON files to React public directory
        run: |
          cp -r backend/JSON/* frontend/option-tech-charts/public/data/

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ">=18.x"

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: frontend/option-tech-charts/node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('frontend/option-tech-charts/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      - name: Install npm dependencies
        working-directory: frontend/option-tech-charts
        run: npm install

      - name: Build React app
        working-directory: frontend/option-tech-charts
        run: npm run build:deploy

      - name: Clone external repository
        run: |
          git clone https://${{ secrets.DEPLOY_TOKEN }}@github.com/Aaakul/Aaakul.github.io.git
          cd Aaakul.github.io
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@noreply.github.com"
      
      - name: Clean destination directory
        run: |
          rm -rf ./Aaakul.github.io/option-tech-charts/*
          mkdir -p ./Aaakul.github.io/option-tech-charts/    

      - name: Copy build files to external repository
        run: |
          cp -r ./frontend/option-tech-charts/build/* ./Aaakul.github.io/option-tech-charts/
          cd Aaakul.github.io
          git add .
          # check git status
          if git diff-index --quiet HEAD; then
            echo "No changes to commit"
          else
            git commit -m "Deploy to GitHub Pages"
            git push --set-upstream origin gh-pages
          fi
